# Project Info:
site_name: ERCAN CANLIER LAB
site_description: ERCAN CANLIER LAB
site_url: https://ercancanlier.github.io/digital-garden/

# Repository Info:
repo_name: ercancanlier/digital-garden
repo_url: https://github.com/ercancanlier/digital-garden

# Configuration
theme:
  name: material
  language: tr
  palette:
    - primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
font:
  text: Overpass
  code: Overpass Mono
icon:
  logo: material/receipt
  repo: fontawesome/brands/github

features:
  - navigation.instant
  - navigation.top
  - navigation.indexes
  - navigation.tracking
  - content.code.copy
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ercancanlier
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ercancanlier/
  alternate:
    - name: English
      link: /en/
    - name: Türkçe
      link: /tr/ 
     
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - meta
  - attr_list

# Plugins
plugins:
  - blog
  - search
  - git-authors
  - glightbox
  - tags:
      tags_file: tags.md

# Navigation
nav: 
- ERCAN CANLIER LAB: index.md
- Computer Science: 
- Contact:

